version: '3.8'

services:
  mysql:
    image: mysql:latest
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: pesto
      MYSQL_USER: ram
      MYSQL_PASSWORD: 123456
    volumes:
      - ./mysql-data:/var/lib/mysql
    ports:
      - "3307:3306"
    networks:
      - pesto

  zipkin:
    image: openzipkin/zipkin
    container_name: zipkin
    ports:
      - 9411:9411
    networks:
      - pesto

networks:
  pesto:
    driver: bridge